

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Child" (
    "id" bigint NOT NULL,
    "first_name" character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone,
    "date_of_birth" "date" NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."Child" OWNER TO "postgres";


ALTER TABLE "public"."Child" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Child_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Class" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "start_datetime" timestamp without time zone NOT NULL,
    "end_datetime" timestamp without time zone NOT NULL,
    "location" character varying NOT NULL,
    "name" character varying NOT NULL,
    "description" character varying NOT NULL,
    "volunteer_hours" real NOT NULL,
    "active" boolean NOT NULL,
    "product_id" "text" NOT NULL,
    "price" double precision NOT NULL
);


ALTER TABLE "public"."Class" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Class_Coach" (
    "id" bigint NOT NULL,
    "class_id" bigint NOT NULL,
    "coach_id" bigint NOT NULL,
    "assigned_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Class_Coach" OWNER TO "postgres";


ALTER TABLE "public"."Class_Coach" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Class_Coaches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Class_User_Child" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "child_id" bigint NOT NULL,
    "class_id" bigint NOT NULL,
    "user_id" "uuid",
    "charge_id" bigint NOT NULL
);


ALTER TABLE "public"."Class_User_Child" OWNER TO "postgres";


ALTER TABLE "public"."Class_User_Child" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Class_User_Child_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Class" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Class_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Coach" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "volunteer_hours" bigint DEFAULT '0'::bigint NOT NULL,
    "total_hours" bigint DEFAULT '0'::bigint NOT NULL,
    "active" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."Coach" OWNER TO "postgres";


ALTER TABLE "public"."Coach" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Coach_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" "uuid" NOT NULL,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "date_of_birth" "date" NOT NULL,
    "phone" character varying NOT NULL,
    "address" character varying NOT NULL
);


ALTER TABLE "public"."User" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Child"
    ADD CONSTRAINT "Child_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Class_Coach"
    ADD CONSTRAINT "Class_Coaches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Class_User_Child"
    ADD CONSTRAINT "Class_User_Child_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Class"
    ADD CONSTRAINT "Class_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Class"
    ADD CONSTRAINT "Class_stripe_product_Id_key" UNIQUE ("product_id");



ALTER TABLE ONLY "public"."Coach"
    ADD CONSTRAINT "Coach_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");



CREATE INDEX "Child_user_id_idx" ON "public"."Child" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."Child"
    ADD CONSTRAINT "Child_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Class_Coach"
    ADD CONSTRAINT "Class_Coach_coach_id_fkey" FOREIGN KEY ("coach_id") REFERENCES "public"."Coach"("id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."Class_Coach"
    ADD CONSTRAINT "Class_Coaches_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."Class"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Class_User_Child"
    ADD CONSTRAINT "Class_User_Child_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "public"."Child"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Class_User_Child"
    ADD CONSTRAINT "Class_User_Child_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."Class"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Class_User_Child"
    ADD CONSTRAINT "Class_User_Child_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."User"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."Child" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Class" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Class_Coach" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Class_User_Child" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Coach" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable read access for all users" ON "public"."Class" FOR SELECT USING (true);



ALTER TABLE "public"."User" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "admin delete only" ON "public"."Class" FOR DELETE TO "supabase_auth_admin" USING (true);



CREATE POLICY "admin delete only" ON "public"."Class_Coach" FOR DELETE TO "supabase_auth_admin" USING (true);



CREATE POLICY "admin delete only" ON "public"."Coach" FOR DELETE TO "supabase_auth_admin" USING (true);



CREATE POLICY "admin insert only" ON "public"."Class" FOR INSERT TO "supabase_auth_admin" WITH CHECK (true);



CREATE POLICY "admin insert only" ON "public"."Class_Coach" FOR INSERT TO "supabase_auth_admin" WITH CHECK (true);



CREATE POLICY "admin insert only" ON "public"."Coach" FOR INSERT TO "supabase_auth_admin" WITH CHECK (true);



CREATE POLICY "admin insert only" ON "public"."User" FOR INSERT TO "supabase_auth_admin" WITH CHECK (true);



CREATE POLICY "admin update only" ON "public"."Class" FOR UPDATE TO "supabase_auth_admin" USING (true) WITH CHECK (true);



CREATE POLICY "admin update only" ON "public"."Class_Coach" FOR UPDATE TO "supabase_auth_admin" USING (true) WITH CHECK (true);



CREATE POLICY "admin update only" ON "public"."Coach" FOR UPDATE TO "supabase_auth_admin" USING (true) WITH CHECK (true);



CREATE POLICY "all authenticated view" ON "public"."Class_Coach" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "authenticated view only" ON "public"."Coach" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "parent admin create only" ON "public"."Child" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin delete only" ON "public"."Class_User_Child" FOR DELETE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin delete only" ON "public"."User" FOR DELETE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin insert only" ON "public"."Class_User_Child" FOR INSERT TO "authenticated" WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin update only" ON "public"."Child" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text"))) WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin update only" ON "public"."Class_User_Child" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text"))) WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent admin update only" ON "public"."User" FOR UPDATE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text"))) WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent and admin delete only" ON "public"."Child" FOR DELETE TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent and admin view only" ON "public"."Child" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent and admin view only" ON "public"."Class_User_Child" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "user_id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));



CREATE POLICY "parent and admin view only" ON "public"."User" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "id") OR (( SELECT "auth"."role"() AS "role") = 'admin'::"text")));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Child" TO "anon";
GRANT ALL ON TABLE "public"."Child" TO "authenticated";
GRANT ALL ON TABLE "public"."Child" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Child_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Child_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Child_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Class" TO "anon";
GRANT ALL ON TABLE "public"."Class" TO "authenticated";
GRANT ALL ON TABLE "public"."Class" TO "service_role";



GRANT ALL ON TABLE "public"."Class_Coach" TO "anon";
GRANT ALL ON TABLE "public"."Class_Coach" TO "authenticated";
GRANT ALL ON TABLE "public"."Class_Coach" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Class_Coaches_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Class_Coaches_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Class_Coaches_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Class_User_Child" TO "anon";
GRANT ALL ON TABLE "public"."Class_User_Child" TO "authenticated";
GRANT ALL ON TABLE "public"."Class_User_Child" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Class_User_Child_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Class_User_Child_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Class_User_Child_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Coach" TO "anon";
GRANT ALL ON TABLE "public"."Coach" TO "authenticated";
GRANT ALL ON TABLE "public"."Coach" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Coach_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Coach_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Coach_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."User" TO "anon";
GRANT ALL ON TABLE "public"."User" TO "authenticated";
GRANT ALL ON TABLE "public"."User" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;

